### ISSUE TITLE
Fix exchanged value estimation in market mode

### ISSUE THREAD

**Issue by jondubois** [Leasehold/lisk-dex-ui#3]
See https://github.com/Jaxkr/lisk-dex-ui/issues/1

**Comment by sacOO7** [comment]
Need to make sure orderbook is updated right before estimation is generated.

**Comment by sacOO7** [comment]
Serious issue with component rendering (PlaceOrder.jsx)-> getting rendered again and again. Need to look into component profiling.

**Comment by sacOO7** [comment]
Fixed component rendering issue and did some quick bug fixes :)
