### ISSUE TITLE
Hide scrollbars when not needed

### ISSUE THREAD

**Issue by ghost** [Leasehold/lisk-dex-ui#32]
![image](https://user-images.githubusercontent.com/42899281/83971330-2cbb5480-a8db-11ea-80df-946088eb2a05.png)

Hiding the browsers scrollbars looks much cleaner. An alternative is to use custom scrollbars.

Solution:  `overflow-y: hidden;`

![image](https://user-images.githubusercontent.com/42899281/83971388-6ee49600-a8db-11ea-94a9-28a625f5e665.png)

**Comment by jondubois** [comment]
Sounds good. Maybe custom scrollbars (dark style) with `overflow-y: auto`.

**Comment by jondubois** [comment]
Done.
