### ISSUE TITLE
Improve Buy and sell boxes

### ISSUE THREAD

**Issue by ghost** [Leasehold/lisk-dex-ui#37]
The Buy and Sell boxes feel a bit unclear. For example, is the price in LSH or LSK? And shouldn't the calculation be price 0.2 x amount 50 = 10 LSK? The pending value behind the calculation in grey is hard to find out what it means without an explanation.

![image](https://user-images.githubusercontent.com/42899281/83972832-b28ece00-a8e2-11ea-8f21-47efcf0c31a3.png)

It's especially important to be clear about the currency when more markets are added.

![image](https://user-images.githubusercontent.com/42899281/83972988-abb48b00-a8e3-11ea-8843-ac8a934df1ff.png)

**Comment by jondubois** [comment]
Done.
