### ISSUE TITLE
Add information about the fee structure

### ISSUE THREAD

**Issue by ghost** [Leasehold/lisk-dex-ui#38]
Users would like to know which fees are deducted for the transactions on the different chains and for the DEX.

**Comment by jondubois** [comment]
I added in the website FAQs https://ldex.exchange/docs/faqs/ for the LSH/LSK market.

Next step we can show info in `lisk-dex-ui` for each market. The DEX node's `/status` endpoint provides this information for each market. Can be a modal overlay which comes up when user clicks on a `[?]` button next to a market's name.

**Comment by jondubois** [comment]
We can also show the two DEX multisig wallet addresses on the same screen along with the other info about each DEX market. Related issue: https://github.com/Leasehold/lisk-dex-ui/issues/30

**Comment by jondubois** [comment]
Done.
