### ISSUE TITLE
Display large numbers better

### ISSUE THREAD

**Issue by jondubois** [Leasehold/lisk-dex-ui#8]
Use commas to break up large numbers to make them more readable.

- User account balances.
- Prices and volumes (both in the order book list and in the chart and tooltip)

**Comment by jondubois** [comment]
The `PriceHistoryChart` component already has a function called `formatThousands` which could be extracted into a separate file and re-used.

**Comment by sacOO7** [comment]
Update - In the chart and tooltip, values are already formatted, moving formatThousand under utils and importing it in respective files
